list1=set(["White","Red","Violet","Black","Blue"])
list2=set(["Yellow","Red","Green","Black"])
print("List1:",list1)
print("List2:",list2)
dif=list1.difference(list2)
print("Colors from list1 not contained in list2: ",dif)